Vagrant.configure("2") do |config|
  config.vm.box = "utopic386"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-i386-vagrant-disk1.box"

  #config.vm.network :forwarded_port, guest: 8080, host: 8080

  config.vm.network "private_network", ip: "172.28.128.1#{rand(99)}", :adapter => 2

  config.vm.synced_folder "../", "/home/vagrant/app/", :nfs => true

  config.vm.provision "shell", path: "setup.sh"
end
